#!/bin/bash

name=$(whiptail --inputbox "What's your name?" 10 50 --title "Access Check" 3>&1 1>&2 2>&3)

if [[ "$name" != "oliver" ]]; then
    whiptail --msgbox "Access denied." 10 50 --title "Access Check"
    systemctl poweroff
    exit 1
fi

word=$(whiptail --inputbox "Hello captain! What's the magic word?" 10 50 --title "Access Chec>

if [[ "$word" != "swordfish" ]]; then
    whiptail --msgbox "Access denied." 10 50 --title "Access Check"
    systemctl poweroff
    exit 1
fi

whiptail --msgbox "Access granted, captain." 10 50 --title "Access Check"
systemctl start lightdm
exit 0 
